// generated by go run gen-fonts.go; DO NOT EDIT

// Package liberationserifregular provides the "LiberationSerif Regular" TrueType font
// from the Liberation font family.
package liberationserifregular // import "ui/util/liberation/liberationserifregular"

import _ "embed"

// TTF is the data for the "LiberationSerif Regular" TrueType font.
//
//go:embed LiberationSerif-Regular.ttf
var TTF []byte
