// generated by go run gen-fonts.go; DO NOT EDIT

// Package liberationmonobold provides the "LiberationMono Bold" TrueType font
// from the Liberation font family.
package liberationmonobold // import "ui/util/liberation/liberationmonobold"

import _ "embed"

// TTF is the data for the "LiberationMono Bold" TrueType font.
//
//go:embed LiberationMono-Bold.ttf
var TTF []byte
